# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-upload_time',),
            },
        ),
    ]
